version: "3.5"

services:
  app:
    # build: ./
    image: node:16-buster
    command: sh -c "yarn && yarn dev"
    ports:
      - 3000:3000
    working_dir: /docker-compose-next-demo
    volumes:
      - ./:/docker-compose-next-demo
